import os
import smtplib
import requests
from email.mime.text import MIMEText

GMAIL = os.environ["GMAIL_ADDRESS"]
PASSWORD = os.environ["GMAIL_APP_PASSWORD"]
MAIL_TO = os.environ["MAIL_TO"]
WORKER_URL = os.environ["WORKER_URL"]

res = requests.get(WORKER_URL, timeout=15)
res.raise_for_status()
data = res.json()

items = []
for task in data.get("tasks", []):
    items.append(f"""
      <li style="margin-bottom:12px;">
        <b>{task["title"]}</b><br>
        <a href="{task["url_do"]}">▶ Do</a> |
        <a href="{task["url_someday"]}">🕒 Someday</a> |
        <a href="{task["url_drop"]}">🗑 Drop</a>
      </li>
    """)

html = f"""
<html>
<body style="font-family: sans-serif;">
  <h2>📥 今日のInbox</h2>
  {"<ul>" + "".join(items) + "</ul>" if items else "<p>今日はInboxゼロです 🎉</p>"}
  <hr>
  <p style="font-size:12px;color:#666;">Generated by GTD Morning Mail</p>
</body>
</html>
"""

msg = MIMEText(html, "html", "utf-8")
msg["Subject"] = f"【GTD】今日のInbox（{len(items)}件）"
msg["From"] = GMAIL
msg["To"] = MAIL_TO

with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
    smtp.login(GMAIL, PASSWORD)
    smtp.send_message(msg)

print("mail sent")
